### ISSUE TITLE
Error in cv2.line function

### ISSUE THREAD

**Issue by avdhootu27** [Pawandeep-prog/draw-in-air#1]
"D:\Python Programs\venv\Scripts\python.exe" "D:/Python Programs/draw_in_air.py"
Traceback (most recent call last):
  File "D:\Python Programs\draw_in_air.py", line 73, in <module>
    mask = cv2.line(mask, (a,b), (x,y), (0, 0, 255), 6)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

getting above error even after copy pasting the code.
there is one observation- if values of a,b,x and y are integer then it don't show this error but then code doesn't work as expected and if values of a,b,x and y are float then i am getting above error

**Comment by muzakkir908** [comment]
Same problem here..how to solve it..any ideas??

**Comment by Pawandeep-prog** [comment]
> Same problem here..how to solve it..any ideas??

you can type cast these values of pt1 and pt2 to int then it will work I'll soon update the code
